// Animation names
#define SINGLESHOTGUN_ANIM_DEFAULT_ANIMATION 0
#define SINGLESHOTGUN_ANIM_WAIT1 1
#define SINGLESHOTGUN_ANIM_WAIT2 2
#define SINGLESHOTGUN_ANIM_WAIT3 3
#define SINGLESHOTGUN_ANIM_ACTIVATE 4
#define SINGLESHOTGUN_ANIM_DEACTIVATE 5
#define SINGLESHOTGUN_ANIM_FIRE1 6
#define SINGLESHOTGUN_ANIM_FIRE1FAST 7

// Color names

// Patch names

// Names of collision boxes
#define SINGLESHOTGUN_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define SINGLESHOTGUN_ATTACHMENT_NOT_LOADED 0
#define SINGLESHOTGUN_ATTACHMENT_NOT_LOADED 1
#define SINGLESHOTGUN_ATTACHMENT_NOT_LOADED 2

// Sound names
