// Animation names
#define TOMMYGUN_ANIM_DEFAULT 0
#define TOMMYGUN_ANIM_FIRE 1
#define TOMMYGUN_ANIM_WAIT1 2
#define TOMMYGUN_ANIM_WAIT2 3
#define TOMMYGUN_ANIM_WAIT3 4
#define TOMMYGUN_ANIM_ACTIVATE 5
#define TOMMYGUN_ANIM_DEACTIVATE 6
#define TOMMYGUN_ANIM_RELOAD 7
#define TOMMYGUN_ANIM_RELOADG 8

// Color names

// Patch names

// Names of collision boxes
#define TOMMYGUN_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define TOMMYGUN_ATTACHMENT_BODY 0
#define TOMMYGUN_ATTACHMENT_SLIDER 1
#define TOMMYGUN_ATTACHMENT_UNDERBARREL 2
#define TOMMYGUN_ATTACHMENT_AG36GRANAT 3

// Sound names
