// Animation names
#define P90DEFAULT_ANIM_P90_ANIM_DEFAULT 0
#define P90DEFAULT_ANIM_P90_ANIM_FIRE 1
#define P90DEFAULT_ANIM_P90_ANIM_WAIT1 2
#define P90DEFAULT_ANIM_P90_ANIM_WAIT2 3
#define P90DEFAULT_ANIM_P90_ANIM_RELOAD 4
#define P90DEFAULT_ANIM_P90_ANIM_ACTIVATE 5
#define P90DEFAULT_ANIM_P90_ANIM_DEACTIVATE 6
#define P90DEFAULT_ANIM_P90_ANIM_WAIT3 7

// Color names

// Patch names

// Names of collision boxes
#define P90DEFAULT_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define P90DEFAULT_ATTACHMENT_P90_BODY 0
#define P90DEFAULT_ATTACHMENT_P90_RELOADM 1
#define P90DEFAULT_ATTACHMENT_P90_ZATVORM 2

// Sound names
