/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"

#include "StdH.h"
#include "Models/Enemies/Mental/Mental.h"
#include "Models/CutSequences/CrateRider/Crate.h"

#include <EntitiesMP/CrateRider.h>
#include <EntitiesMP/CrateRider_tables.h>
#line 11 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"

// info structure
static EntityInfo eiCrate = {
  EIBT_FLESH, 500.0f,
  0.0f, 1.5f, 0.0f,     // source (eyes)
  0.0f, 1.0f, 0.0f,     // target (body)
};

#define GREET_SENSE_RANGE 10.0f
#define GREET_SENSE_DELAY 10.0f


void CCrateRider::SetDefaultProperties(void) {
  m_fnmHeadTex1 = CTString("");
  m_fnmHeadTex2 = CTString("");
  m_fnmDriveSnd = CTString("");
  CEnemyBase::SetDefaultProperties();
}
  
#line 56 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void * CCrateRider::GetEntityInfo(void) 
#line 57 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
{
#line 58 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
return & eiCrate ;
#line 59 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 61 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::Precache(void) 
#line 62 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
{
#line 63 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
CEnemyBase  :: Precache  ();
#line 65 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
PrecacheClass  (CLASS_DEBRIS );
#line 67 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_apt1  . Precache  (m_fnmHeadTex1 );
#line 68 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_apt2  . Precache  (m_fnmHeadTex2 );
#line 69 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_aps  . Precache  (m_fnmDriveSnd );
#line 70 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 73 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
INDEX CCrateRider::AnimForDamage(FLOAT fDamage) {
#line 74 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
INDEX iAnim ;
#line 75 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
iAnim  = 0;
#line 76 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
StartModelAnim  (iAnim  , 0);
#line 77 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
return iAnim ;
#line 78 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 81 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
INDEX CCrateRider::AnimForDeath(void) {
#line 82 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
INDEX iAnim ;
#line 83 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
iAnim  = 0;
#line 84 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
StartModelAnim  (iAnim  , 0);
#line 85 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
return iAnim ;
#line 86 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 88 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::DeathNotify(void) {
#line 90 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
en_fDensity  = 500.0f;
#line 91 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 94 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::StandingAnim(void) {
#line 95 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
StartModelAnim  (CRATE_ANIM_DEFAULT  , AOF_LOOPING  | AOF_NORESTART  | AOF_SMOOTHCHANGE );
#line 97 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmo0  = & (GetModelObject  () -> GetAttachmentModel  (0) -> amo_moModelObject );
#line 98 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
pmo0  -> PlayAnim  (MENTAL_ANIM_CRATEANIMLEFTSEATING  , AOF_LOOPING  | AOF_NORESTART  | AOF_SMOOTHCHANGE );
#line 99 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmo1  = & (GetModelObject  () -> GetAttachmentModel  (1) -> amo_moModelObject );
#line 100 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
pmo1  -> PlayAnim  (MENTAL_ANIM_CRATEANIMRIGHTSEATING  , AOF_LOOPING  | AOF_NORESTART  | AOF_SMOOTHCHANGE );
#line 102 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_soSound  . Stop  ();
#line 103 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 104 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::WalkingAnim(void) {
#line 105 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
RunningAnim  ();
#line 106 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
StartModelAnim  (CRATE_ANIM_DRIVE  , AOF_LOOPING  | AOF_NORESTART );
#line 107 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 108 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::RunningAnim(void) 
#line 109 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
{
#line 110 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
if(m_fnmDriveSnd  != ""){
#line 111 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
PlaySound  (m_soSound  , m_fnmDriveSnd  , SOF_3D );
#line 112 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
#line 113 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmo0  = & (GetModelObject  () -> GetAttachmentModel  (0) -> amo_moModelObject );
#line 114 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
pmo0  -> PlayAnim  (MENTAL_ANIM_CRATEANIMLEFT  , AOF_LOOPING  | AOF_NORESTART );
#line 115 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmo1  = & (GetModelObject  () -> GetAttachmentModel  (1) -> amo_moModelObject );
#line 116 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
pmo1  -> PlayAnim  (MENTAL_ANIM_CRATEANIMRIGHT  , AOF_LOOPING  | AOF_NORESTART );
#line 118 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
StartModelAnim  (CRATE_ANIM_DRIVE  , AOF_LOOPING  | AOF_NORESTART );
#line 119 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 120 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::RotatingAnim(void) {
#line 121 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
RunningAnim  ();
#line 122 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 125 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::IdleSound(void) {
#line 127 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 129 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::SightSound(void) {
#line 131 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 132 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::WoundSound(void) {
#line 134 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 135 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::DeathSound(void) {
#line 137 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
  
#line 139 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
void CCrateRider::AddRider(INDEX i,const CTFileName & fnmHead) 
#line 140 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
{
#line 141 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
AddAttachment  (i  , MODEL_MENTAL  , TEXTURE_MENTAL );
#line 142 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmoMain  = & (GetModelObject  () -> GetAttachmentModel  (i ) -> amo_moModelObject );
#line 144 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
pmoMain  -> PlayAnim  (i  == 0 ? MENTAL_ANIM_CRATEANIMLEFT  : MENTAL_ANIM_CRATEANIMRIGHT  , AOF_LOOPING );
#line 145 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
AddAttachmentToModel  (this  , * pmoMain  , 0 , MODEL_HEAD  , TEXTURE_MENTAL  , 0 , 0 , 0);
#line 146 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
CModelObject * pmoHead  = & (pmoMain  -> GetAttachmentModel  (0) -> amo_moModelObject );
#line 147 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
if(fnmHead  != ""){
#line 149 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
try {
#line 150 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
pmoHead  -> mo_toTexture  . SetData_t  (fnmHead );
#line 152 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}catch  (char  * strError ){
#line 154 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
CPrintF  ("%s\n" , strError );
#line 155 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
#line 156 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
#line 157 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
}
BOOL CCrateRider::
#line 164 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CCrateRider_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CCrateRider::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 166 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
InitAsModel  ();
#line 167 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 168 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
SetCollisionFlags  (ECF_MODEL );
#line 169 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 170 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
SetHealth  (1.0f);
#line 171 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fMaxHealth  = 1.0f;
#line 172 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
en_tmMaxHoldBreath  = 5.0f;
#line 173 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
en_fDensity  = 2000.0f;
#line 174 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fBlowUpSize  = 2.0f;
#line 177 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
SetModel  (MODEL_CRATE );
#line 178 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
SetModelMainTexture  (TEXTURE_CRATE );
#line 179 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
AddRider  (0 , m_fnmHeadTex1 );
#line 180 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
AddRider  (1 , m_fnmHeadTex2 );
#line 183 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fWalkSpeed  = 
#line 184 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fAttackRunSpeed  = 
#line 185 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fCloseRunSpeed  = 1.0f;
#line 186 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_aWalkRotateSpeed  = AngleDeg  (30.0f);
#line 187 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_aAttackRotateSpeed  = AngleDeg  (30);
#line 188 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_aCloseRotateSpeed  = AngleDeg  (30);
#line 190 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fAttackDistance  = 50.0f;
#line 191 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fCloseDistance  = 0.0f;
#line 192 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fStopDistance  = 5.0f;
#line 193 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fAttackFireTime  = 2.0f;
#line 194 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fCloseFireTime  = 1.0f;
#line 195 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fIgnoreRange  = 200.0f;
#line 197 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fBlowUpAmount  = 0.0f;
#line 198 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fBodyParts  = 4;
#line 199 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_fDamageWounded  = 1.0f;
#line 200 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_iScore  = 0;
#line 201 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_bBlind  = TRUE ;
#line 202 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
m_bRobotBlowup  = TRUE ;
#line 206 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
const FLOAT fSize  = 0.6f;
#line 207 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
GetModelObject  () -> StretchModel  (FLOAT3D (fSize  , fSize  , fSize ));
#line 208 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
ModelChangeNotify  ();
#line 209 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
StandingAnim  ();
#line 212 "V:/Programs/SamSDK/Sources/EntitiesMP/CrateRider.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};