/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"

#include "StdH.h"
#include "EntitiesMP/Effector.h"
#include <EntitiesMP/BloodSpray.h>

#include <EntitiesMP/Effector.h>
#include <EntitiesMP/Effector_tables.h>
CEntityEvent *ESpawnEffector::MakeCopy(void) { CEntityEvent *peeCopy = new ESpawnEffector(*this); return peeCopy;}
ESpawnEffector::ESpawnEffector() : CEntityEvent(EVENTCODE_ESpawnEffector) {;
 ClearToDefault(eetType);
 ClearToDefault(vDamageDir);
 ClearToDefault(vDestination);
 ClearToDefault(tmLifeTime);
 ClearToDefault(fSize);
 ClearToDefault(ctCount);
 ClearToDefault(penModel);
 ClearToDefault(penModel2);
};
#line 37 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"

void CEffector_OnPrecache(CDLLEntityClass *pdec, INDEX iUser) 
{
  switch ((EffectorEffectType)iUser)
  {
  case ET_MOVING_RING           :
    pdec->PrecacheModel(MODEL_POWER_RING);
    pdec->PrecacheTexture(TEXTURE_POWER_RING);
    break;
  case ET_DESTROY_OBELISK       :
  case ET_DESTROY_PYLON         :
  case ET_HIT_GROUND            :
  case ET_LIGHTNING             :
  case ET_SIZING_BIG_BLUE_FLARE :
  case ET_SIZING_RING_FLARE     :
  case ET_PORTAL_LIGHTNING      :
  case ET_MORPH_MODELS          :
  case ET_DISAPPEAR_MODEL       :
  case ET_APPEAR_MODEL          :
  case ET_DISAPPEAR_MODEL_NOW   :
  case ET_APPEAR_MODEL_NOW      :
    // no precaching needed
    break;
  default:
    ASSERT(FALSE);
  }
}

// array for model vertices in absolute space
CStaticStackArray<FLOAT3D> avModelFXVertices;

void CEffector::SetDefaultProperties(void) {
  m_eetType = ET_NONE ;
  m_tmStarted = 0.0f;
  m_vDamageDir = FLOAT3D(0 , 0 , 0);
  m_vFXDestination = FLOAT3D(0 , 0 , 0);
  m_tmLifeTime = 5.0f;
  m_fSize = 1.0f;
  m_ctCount = 0;
  m_bLightSource = FALSE ;
  m_aoLightAnimation.SetData(NULL);

  m_iLightAnimation = -1;
  m_bAlive = TRUE ;
  m_penModel = NULL;
  m_penModel2 = NULL;
  m_bWaitTrigger = FALSE ;
  CMovableModelEntity::SetDefaultProperties();
}
  
#line 104 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT CEffector::CalculateLifeRatio(FLOAT fFadeInRatio,FLOAT fFadeOutRatio) 
#line 105 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 106 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
TIME  tmDelta  = _pTimer  -> GetLerpedCurrentTick  () - m_tmStarted ;
#line 107 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio  = CalculateRatio  (tmDelta  , 0 , m_tmLifeTime  , fFadeInRatio  , fFadeOutRatio );
#line 108 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
return fLifeRatio ;
#line 109 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
  
#line 111 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
void CEffector::AdjustMipFactor(FLOAT & fMipFactor) 
#line 112 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 113 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_DISAPPEAR_MODEL  || m_eetType  == ET_DISAPPEAR_MODEL_NOW  && m_penModel  != NULL )
#line 114 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 115 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
CModelObject * pmo  = m_penModel  -> GetModelObject  ();
#line 116 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
TIME  tmDelta  = _pTimer  -> GetLerpedCurrentTick  () - m_tmStarted ;
#line 117 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio ;
#line 118 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_tmStarted  == - 1)
#line 119 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 120 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 1.0f;
#line 121 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 122 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
else if(tmDelta  >= m_tmLifeTime )
#line 123 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 124 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 0.0f;
#line 125 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 126 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
else 
#line 127 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 128 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fLifeRatio  = CalculateLifeRatio  (0.0f , 1.0f);
#line 129 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 130 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
UBYTE  ubAlpha  = UBYTE  (255.0f * fLifeRatio );
#line 131 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
COLOR col  = C_WHITE  | ubAlpha ;
#line 132 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
pmo  -> mo_colBlendColor  = col ;
#line 133 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 134 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_APPEAR_MODEL  || m_eetType  == ET_APPEAR_MODEL_NOW  && m_penModel  != NULL )
#line 135 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 136 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
CModelObject * pmo  = m_penModel  -> GetModelObject  ();
#line 137 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
TIME  tmDelta  = _pTimer  -> GetLerpedCurrentTick  () - m_tmStarted ;
#line 138 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio ;
#line 139 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_tmStarted  == - 1)
#line 140 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 141 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 0.0f;
#line 142 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 143 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
else if(tmDelta  >= m_tmLifeTime )
#line 144 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 145 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 1.0f;
#line 146 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 147 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
else 
#line 148 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 149 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fLifeRatio  = CalculateLifeRatio  (1.0f , 0.0f);
#line 150 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 151 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
UBYTE  ubAlpha  = UBYTE  (255.0f * fLifeRatio );
#line 152 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
COLOR col  = C_WHITE  | ubAlpha ;
#line 153 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
pmo  -> mo_colBlendColor  = col ;
#line 154 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 155 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MORPH_MODELS  && m_penModel  != NULL  && m_penModel2  != NULL )
#line 156 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 157 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
CModelObject * pmo1  = m_penModel  -> GetModelObject  ();
#line 158 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
CModelObject * pmo2  = m_penModel2  -> GetModelObject  ();
#line 159 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
TIME  tmDelta  = _pTimer  -> GetLerpedCurrentTick  () - m_tmStarted ;
#line 160 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio ;
#line 161 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_tmStarted  == - 1)
#line 162 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 163 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 0.0f;
#line 164 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 165 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
else if(tmDelta  >= m_tmLifeTime )
#line 166 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 167 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fLifeRatio  = 1.0f;
#line 168 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 169 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
else 
#line 170 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 171 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fLifeRatio  = CalculateLifeRatio  (1.0f , 0.0f);
#line 172 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 173 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
UBYTE  ubAlpha1  = UBYTE  (255.0f * (1 - fLifeRatio ));
#line 174 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
UBYTE  ubAlpha2  = 255 - ubAlpha1 ;
#line 175 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
COLOR col1  = C_WHITE  | ubAlpha1 ;
#line 176 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
COLOR col2  = C_WHITE  | ubAlpha2 ;
#line 177 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
pmo1  -> mo_colBlendColor  = col1 ;
#line 178 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
pmo2  -> mo_colBlendColor  = col2 ;
#line 179 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 180 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
  
#line 182 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
BOOL CEffector::AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient) 
#line 183 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 184 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MOVING_RING )
#line 185 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 186 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio  = CalculateLifeRatio  (0.2f , 0.1f);
#line 187 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fT  = _pTimer  -> CurrentTick  () - m_tmStarted ;
#line 188 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fPulse  = 1.0f;
#line 189 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
UBYTE  ub  = UBYTE  (255.0f * fPulse  * fLifeRatio );
#line 190 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
COLOR col  = RGBAToColor  (ub  , ub  , ub  , ub );
#line 191 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
GetModelObject  () -> mo_colBlendColor  = col ;
#line 192 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 194 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
return FALSE ;
#line 195 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
  
#line 197 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
void CEffector::RenderMovingLightnings(void) 
#line 198 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 200 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fLifeRatio  = CalculateLifeRatio  (0.1f , 0.1f);
#line 202 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_penModel  -> GetModelVerticesAbsolute  (avModelFXVertices  , 0.05f , 0.0f);
#line 203 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
const FLOATmatrix3D & m  = m_penModel  -> GetRotationMatrix  ();
#line 204 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT3D vOrigin  = m_penModel  -> GetPlacement  () . pl_PositionVector ;
#line 205 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fFXTime  = 0.75f;
#line 206 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fMaxHeight  = 6.0f;
#line 207 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fdh  = 1.0f;
#line 208 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT tmDelta  = _pTimer  -> GetLerpedCurrentTick  () - m_tmStarted ;
#line 209 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fY0  = tmDelta ;
#line 211 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
for(FLOAT fT  = tmDelta ;fT  > 0;fT  -= fFXTime )
#line 212 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 213 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fY  = fT  * 2.0f;
#line 214 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(fY  > fMaxHeight )
#line 215 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 216 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
continue ;
#line 217 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 219 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fHeightRatio  = CalculateRatio  (fY  , 0 , fMaxHeight  , 0.1f , 0.0f);
#line 220 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fMinY  = 1e6f;
#line 221 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fMinY2  = - 1e6f;
#line 222 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
INDEX iLower  = - 1;
#line 223 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
INDEX iUpper  = - 1;
#line 224 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
for(INDEX iVtx  = 0;iVtx  < avModelFXVertices  . Count  ();iVtx  ++)
#line 225 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 227 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT3D v  = (avModelFXVertices  [ iVtx  ] - vOrigin ) * ! m ;
#line 228 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(v  (2) > fY  && v  (2) < fMinY  && v  (1) < 0)
#line 229 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 230 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
iLower  = iVtx ;
#line 231 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fMinY  = v  (2);
#line 232 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 233 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(v  (2) <= fY  && v  (2) > fMinY2  && v  (1) < 0)
#line 234 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 235 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
iUpper  = iVtx ;
#line 236 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fMinY2  = v  (2);
#line 237 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 238 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 240 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(iLower  != - 1 && iUpper  != - 1)
#line 241 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 242 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT3D vRelHi  = (avModelFXVertices  [ iUpper  ] - vOrigin ) * ! m ;
#line 243 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT3D vRelLow  = (avModelFXVertices  [ iLower  ] - vOrigin ) * ! m ;
#line 244 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fLerpFactor  = (fY  - vRelLow  (2)) / (vRelHi  (2) - vRelLow  (2));
#line 245 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT3D vRel  = Lerp  (vRelLow  , vRelHi  , fLerpFactor );
#line 246 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
vRel  (2) = fY ;
#line 247 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT3D vAbs1  = vOrigin  + vRel  * m ;
#line 248 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
vRel  (1) = - vRel  (1);
#line 249 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT3D vAbs2  = vOrigin  + vRel  * m ;
#line 251 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
Particles_Ghostbuster  (vAbs1  , vAbs2  , 16 , 0.325f , fHeightRatio  * fLifeRatio  , 5.0f);
#line 252 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 253 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 254 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
avModelFXVertices  . Clear  ();
#line 255 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
  
#line 258 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
void CEffector::RenderParticles(void) 
#line 259 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 261 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fRatio ;
#line 262 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
TIME  tmNow  = _pTimer  -> GetLerpedCurrentTick  ();
#line 263 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
TIME  tmDelta  = tmNow  - m_tmStarted ;
#line 264 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fLivingRatio  = tmDelta  / m_tmLifeTime ;
#line 265 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(fLivingRatio  < 0.25f){
#line 266 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fRatio  = Clamp  (fLivingRatio  / 0.25f , 0.0f , 1.0f);
#line 267 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}else if(fLivingRatio  > 0.75f){
#line 268 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fRatio  = Clamp  ((- fLivingRatio  + 1.0f) / 0.25f , 0.0f , 1.0f);
#line 269 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}else {
#line 270 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
fRatio  = 1.0f;
#line 271 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 273 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
switch(m_eetType )
#line 274 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 275 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
case ET_DESTROY_OBELISK : 
#line 276 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
Particles_DestroyingObelisk  (this  , m_tmStarted );
#line 277 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
break ;
#line 278 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
case ET_DESTROY_PYLON : 
#line 279 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
Particles_DestroyingPylon  (this  , m_vDamageDir  , m_tmStarted );
#line 280 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
break ;
#line 281 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
case ET_HIT_GROUND : 
#line 282 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
Particles_HitGround  (this  , m_tmStarted  , m_fSize );
#line 283 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
break ;
#line 284 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
case ET_LIGHTNING : 
#line 285 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
Particles_Ghostbuster  (GetPlacement  () . pl_PositionVector  , m_vFXDestination  , m_ctCount  , m_fSize  , fRatio );
#line 286 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
break ;
#line 287 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
case ET_PORTAL_LIGHTNING : 
#line 288 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
RenderMovingLightnings  ();
#line 289 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
break ;
#line 290 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 291 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
  
#line 294 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
void CEffector::Read_t(CTStream * istr) 
#line 295 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 296 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
CMovableModelEntity  :: Read_t  (istr );
#line 298 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_bLightSource ){
#line 299 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetupLightSource  ();
#line 300 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 301 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
  
#line 304 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
CLightSource * CEffector::GetLightSource(void) 
#line 305 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 306 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_bLightSource  && ! IsPredictor  ()){
#line 307 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
return & m_lsLightSource ;
#line 308 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}else {
#line 309 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
return NULL ;
#line 310 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 311 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
  
#line 314 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
void CEffector::SetupLightSource(void) 
#line 315 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 316 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_iLightAnimation  >= 0)
#line 317 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 318 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
try {
#line 319 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_aoLightAnimation  . SetData_t  (CTFILENAME  ("Animations\\Effector.ani"));
#line 320 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}catch  (char  * strError ){
#line 321 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
WarningMessage  (TRANS  ("Cannot load Animations\\Effector.ani: %s") , strError );
#line 322 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 324 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_aoLightAnimation  . GetData  () != NULL ){
#line 325 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_aoLightAnimation  . PlayAnim  (m_iLightAnimation  , 0);
#line 326 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 327 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 330 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
CLightSource  lsNew ;
#line 331 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_ulFlags  = LSF_LENSFLAREONLY ;
#line 332 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_rHotSpot  = 0.0f;
#line 333 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
switch(m_eetType ){
#line 334 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
case ET_SIZING_RING_FLARE : 
#line 335 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_colColor  = C_WHITE  | CT_OPAQUE ;
#line 336 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_rHotSpot  = 100.0f;
#line 337 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_rFallOff  = 300.0f;
#line 338 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStarNG ;
#line 339 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
break ;
#line 341 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
case ET_SIZING_BIG_BLUE_FLARE : 
#line 342 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_colColor  = C_WHITE  | CT_OPAQUE ;
#line 343 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_rHotSpot  = 500.0f * m_fSize ;
#line 344 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_rFallOff  = 1000.0f * m_fSize ;
#line 345 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_plftLensFlare  = & _lftBlueStarBlueReflections ;
#line 346 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
break ;
#line 348 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
default  : 
#line 349 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
ASSERTALWAYS  ("Unknown light source");
#line 350 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 351 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_ubPolygonalMask  = 0;
#line 352 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_paoLightAnimation  = NULL ;
#line 355 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_paoLightAnimation  = NULL ;
#line 356 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_aoLightAnimation  . GetData  () != NULL ){
#line 357 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
lsNew  . ls_paoLightAnimation  = & m_aoLightAnimation ;
#line 358 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 360 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_lsLightSource  . ls_penEntity  = this ;
#line 361 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_lsLightSource  . SetLightSource  (lsNew );
#line 362 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
BOOL CEffector::
#line 369 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEffector_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_ESpawnEffector, "CEffector::Main expects 'ESpawnEffector' as input!");  const ESpawnEffector &eSpawn = (const ESpawnEffector &)__eeInput;
#line 372 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
InitAsEditorModel  ();
#line 374 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL  | EPF_MOVABLE );
#line 375 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetCollisionFlags  (ECF_TOUCHMODEL );
#line 376 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetFlags  (GetFlags  () | ENF_SEETHROUGH );
#line 378 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetModel  (MODEL_MARKER );
#line 379 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetModelMainTexture  (TEXTURE_MARKER );
#line 382 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_eetType  = eSpawn  . eetType ;
#line 383 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_vDamageDir  = eSpawn  . vDamageDir ;
#line 384 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_tmStarted  = _pTimer  -> CurrentTick  ();
#line 385 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_tmLifeTime  = eSpawn  . tmLifeTime ;
#line 386 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_vFXDestination  = eSpawn  . vDestination ;
#line 387 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_fSize  = eSpawn  . fSize ;
#line 388 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_ctCount  = eSpawn  . ctCount ;
#line 389 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_bAlive  = TRUE ;
#line 390 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_penModel  = eSpawn  . penModel ;
#line 391 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_penModel2  = eSpawn  . penModel2 ;
#line 392 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_bWaitTrigger  = FALSE ;
#line 394 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x02600001, FALSE, EBegin());return TRUE;}BOOL CEffector::H0x02600001_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x02600002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CEffector::H0x02600002_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600002
;
#line 396 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MOVING_RING )
#line 397 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 398 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetModel  (MODEL_POWER_RING );
#line 399 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetModelMainTexture  (TEXTURE_POWER_RING );
#line 400 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
en_fAcceleration  = 1e6f;
#line 401 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fSpeed  = 550.0f;
#line 402 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetDesiredTranslation  (FLOAT3D (0 , - fSpeed  , 0));
#line 403 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fPathLen  = GetPlacement  () . pl_PositionVector  (2) - m_vFXDestination  (2);
#line 405 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_tmLifeTime  = fPathLen  / fSpeed ;
#line 406 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SwitchToModel  ();
#line 407 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT fSize  = 36.0f;
#line 408 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
FLOAT3D vStretch  = FLOAT3D (fSize  , fSize  * 2.0f , fSize );
#line 409 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
GetModelObject  () -> StretchModel  (vStretch );
#line 410 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
ModelChangeNotify  ();
#line 411 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 413 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_SIZING_RING_FLARE )
#line 414 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 415 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_bLightSource  = TRUE ;
#line 416 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_iLightAnimation  = 0;
#line 417 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 418 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_SIZING_BIG_BLUE_FLARE )
#line 419 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 420 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_bLightSource  = TRUE ;
#line 421 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_iLightAnimation  = 1;
#line 422 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 423 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MORPH_MODELS  || m_eetType  == ET_DISAPPEAR_MODEL  || m_eetType  == ET_APPEAR_MODEL )
#line 424 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 425 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_bWaitTrigger  = TRUE ;
#line 426 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_tmStarted  = - 1;
#line 427 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 428 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_DISAPPEAR_MODEL_NOW  || m_eetType  == ET_APPEAR_MODEL_NOW )
#line 429 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 430 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_bWaitTrigger  = FALSE ;
#line 431 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_tmStarted  = _pTimer  -> CurrentTick  ();
#line 432 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 435 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_bLightSource ){SetupLightSource  ();}
#line 437 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
Jump(STATE_CURRENT,0x02600005, FALSE, EInternal());return TRUE;}BOOL CEffector::H0x02600005_Main_05(const CEntityEvent &__eeInput)
#line 438 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600005
if(!(_pTimer  -> CurrentTick  () < m_tmStarted  + m_tmLifeTime  && m_bAlive  || m_bWaitTrigger )){ Jump(STATE_CURRENT,0x02600006, FALSE, EInternal());return TRUE;}
#line 439 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
SetTimerAfter(0.25f);
Jump(STATE_CURRENT, 0x02600003, FALSE, EBegin());return TRUE;}BOOL CEffector::H0x02600003_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600003
switch(__eeInput.ee_slEvent)
#line 440 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETrigger):
#line 443 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{const ETrigger&e= (ETrigger&)__eeInput;

#line 444 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MORPH_MODELS  || m_eetType  == ET_DISAPPEAR_MODEL  || m_eetType  == ET_APPEAR_MODEL )
#line 445 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 446 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_tmStarted  = _pTimer  -> CurrentTick  ();
#line 447 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_bWaitTrigger  = FALSE ;
#line 449 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_bAlive  = TRUE ;
#line 450 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 451 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
return TRUE;
#line 452 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x02600004, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 454 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}return TRUE;}BOOL CEffector::H0x02600004_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600004

#line 456 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(m_eetType  == ET_MOVING_RING )
#line 457 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 458 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
if(GetPlacement  () . pl_PositionVector  (2) < m_vFXDestination  (2))
#line 459 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
{
#line 460 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
m_bAlive  = FALSE ;
#line 461 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}
#line 462 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}Jump(STATE_CURRENT,0x02600005, FALSE, EInternal());return TRUE;
#line 463 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
}BOOL CEffector::H0x02600006_Main_06(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x02600006

#line 465 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
Destroy  ();
#line 466 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
Return(STATE_CURRENT,EVoid());
#line 466 "V:/Programs/SamSDK/Sources/EntitiesMP/Effector.es"
return TRUE; ASSERT(FALSE); return TRUE;};