/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"

#include "StdH.h"
#include "ModelsMP/Enemies/Grunt/elite_merc/merc_elite.h"
#include "ModelsMP/Enemies/Grunt/merc/merc_idle.h"

#include <EntitiesMP/Grunt.h>
#include <EntitiesMP/Grunt_tables.h>
#line 22 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"

#define STRETCH_SOLDIER   1.2f
#define STRETCH_COMMANDER 1.4f
#define FIREPOS_SOLDIER      FLOAT3D(0.07f, 1.36f, -0.78f)*STRETCH_SOLDIER
#define FIREPOS_COMMANDER    FLOAT3D(0.10f, 1.30f, -0.60f)*STRETCH_COMMANDER
#define SHOTGUN_SPREAD_ANGLE 5.0f // angle for shotgun
#define BULLET_DAMAGE 4.0f  // Damage per bullet

// info structure
static EntityInfo eiGruntSoldier = {
  EIBT_FLESH, 200.0f,
  0.0f, 1.9f*STRETCH_SOLDIER, 0.0f,     // source (eyes)
  0.0f, 1.3f*STRETCH_SOLDIER, 0.0f,     // target (body)
};

static EntityInfo eiGruntCommander = {
  EIBT_FLESH, 250.0f,
  0.0f, 1.9f*STRETCH_COMMANDER, 0.0f,     // source (eyes)
  0.0f, 1.3f*STRETCH_COMMANDER, 0.0f,     // target (body)
};

#define FIREPOS_SOLDIER      FLOAT3D(0.07f, 1.36f, -0.78f)*STRETCH_SOLDIER
#define FIREPOS_COMMANDER_UP  FLOAT3D(0.09f, 1.45f, -0.62f)*STRETCH_COMMANDER
#define FIREPOS_COMMANDER_DN  FLOAT3D(0.10f, 1.30f, -0.60f)*STRETCH_COMMANDER

void CGrunt::SetDefaultProperties(void) {
  m_gtType = GT_SOLDIER ;
  m_gwtWeapon = GWT_AUTO_RIFLE ;
  m_bFireBulletCount = 0;
  m_fFireTime = 0.0f;
  m_soFire1.SetOwner(this);
m_soFire1.Stop_internal();
  m_soFire2.SetOwner(this);
m_soFire2.Stop_internal();
  CEnemyBase::SetDefaultProperties();
}
  CTString CGrunt::GetPlayerKillDescription(const CTString & strPlayerName,const EDeath & eDeath) 
#line 99 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
{
#line 100 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CTString str ;
#line 101 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
str  . PrintF  (TRANS  ("A Grunt sent %s into the halls of Valhalla") , strPlayerName );
#line 102 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return str ;
#line 103 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 106 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void * CGrunt::GetEntityInfo(void) {
#line 107 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 108 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return & eiGruntSoldier ;
#line 109 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else if(m_gtType  == GT_COMMANDER ){
#line 110 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return & eiGruntSoldier ;
#line 111 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else {
#line 112 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
ASSERT  ("Unknown grunt type!");
#line 113 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return NULL ;
#line 114 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 115 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  const CTFileName & CGrunt::GetComputerMessageName(void)const {
#line 118 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
static DECLARE_CTFILENAME  (fnmSoldier  , "DataMP\\Messages\\Enemies\\GruntSoldier.txt");
#line 119 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
static DECLARE_CTFILENAME  (fnmCommander  , "DataMP\\Messages\\Enemies\\GruntCommander.txt");
#line 120 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
switch(m_gtType ){
#line 121 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
default  : ASSERT  (FALSE );
#line 122 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
case GT_SOLDIER : return fnmSoldier ;
#line 123 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
case GT_COMMANDER : return fnmCommander ;
#line 124 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 125 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 127 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::Precache(void) {
#line 128 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CEnemyBase  :: Precache  ();
#line 130 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 131 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_GRUNT_PROJECTILE_SOL );
#line 132 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 133 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_COMMANDER ){
#line 134 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PrecacheClass  (CLASS_PROJECTILE  , PRT_GRUNT_PROJECTILE_COM );
#line 135 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 137 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PrecacheClass  (CLASS_BULLET );
#line 139 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PrecacheSound  (SOUND_IDLE );
#line 140 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PrecacheSound  (SOUND_SIGHT );
#line 141 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PrecacheSound  (SOUND_WOUND );
#line 142 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PrecacheSound  (SOUND_FIRE );
#line 143 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PrecacheSound  (SOUND_DEATH );
#line 144 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 147 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 148 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 149 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
{
#line 150 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CEnemyBase  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 151 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 154 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
INDEX CGrunt::AnimForDamage(FLOAT fDamage) {
#line 155 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
INDEX iAnim ;
#line 156 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){iAnim  = MERC_ELITE_ANIM_WOUND01 ;}
#line 157 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_COMMANDER ){iAnim  = MERC_IDLE_ANIM_WOUND01 ;}
#line 158 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (iAnim  , 0);
#line 159 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return iAnim ;
#line 160 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 163 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
INDEX CGrunt::AnimForDeath(void) {
#line 164 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
INDEX iAnim ;
#line 165 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
FLOAT3D vFront ;
#line 166 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
GetHeadingDirection  (0 , vFront );
#line 167 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
FLOAT fDamageDir  = m_vDamage  % vFront ;
#line 168 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 169 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(fDamageDir  < 0){
#line 170 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
iAnim  = MERC_ELITE_ANIM_DEATHBACKWARD ;
#line 171 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else {
#line 172 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
iAnim  = MERC_ELITE_ANIM_DEATHFORWARD ;
#line 173 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 174 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 175 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_COMMANDER ){
#line 176 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(fDamageDir  < 0){
#line 177 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
iAnim  = MERC_IDLE_ANIM_DEATHBACKWARD ;
#line 178 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else {
#line 179 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
iAnim  = MERC_IDLE_ANIM_DEATHFORWARD ;
#line 180 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 181 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 183 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (iAnim  , 0);
#line 184 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return iAnim ;
#line 185 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 187 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
FLOAT CGrunt::WaitForDust(FLOAT3D & vStretch) {
#line 188 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
vStretch  = FLOAT3D (1 , 1 , 2);
#line 189 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 190 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(GetModelObject  () -> GetAnim  () == MERC_ELITE_ANIM_DEATHBACKWARD ){
#line 191 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return 0.5f;
#line 192 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else if(GetModelObject  () -> GetAnim  () == MERC_ELITE_ANIM_DEATHFORWARD ){
#line 193 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return 1.0f;
#line 194 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 195 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 196 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_COMMANDER ){
#line 197 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(GetModelObject  () -> GetAnim  () == MERC_IDLE_ANIM_DEATHBACKWARD ){
#line 198 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return 0.5f;
#line 199 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else if(GetModelObject  () -> GetAnim  () == MERC_IDLE_ANIM_DEATHFORWARD ){
#line 200 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return 1.0f;
#line 201 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 202 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 203 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return - 1.0f;
#line 204 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 206 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::DeathNotify(void) {
#line 207 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_soFire1  . Stop  ();
#line 208 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_soFire2  . Stop  ();
#line 209 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){ChangeCollisionBoxIndexWhenPossible  (MERC_ELITE_COLLISION_BOX_DEATH );}
#line 210 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_COMMANDER ){ChangeCollisionBoxIndexWhenPossible  (MERC_IDLE_COLLISION_BOX_DEATH );}
#line 211 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
en_fDensity  = 500.0f;
#line 212 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 215 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::StandingAnim(void) {
#line 216 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 217 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_ELITE_ANIM_IDLEPATROL  , AOF_LOOPING  | AOF_NORESTART );
#line 218 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 219 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_COMMANDER ){
#line 220 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_IDLE_ANIM_IDLE2  , AOF_LOOPING  | AOF_NORESTART );
#line 221 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 222 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 224 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::StandingAnimFight(void) {
#line 225 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 226 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_ELITE_ANIM_FIRE  , AOF_LOOPING  | AOF_NORESTART );
#line 227 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 228 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_COMMANDER ){
#line 229 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_IDLE_ANIM_FIRE  , AOF_LOOPING  | AOF_NORESTART );
#line 230 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 231 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 233 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::RunningAnim(void) {
#line 234 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 235 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_ELITE_ANIM_RUN  , AOF_LOOPING  | AOF_NORESTART );
#line 236 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 237 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_COMMANDER ){
#line 238 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_IDLE_ANIM_RUN  , AOF_LOOPING  | AOF_NORESTART );
#line 239 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 240 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 242 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::WalkingAnim(void) {
#line 243 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 244 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_ELITE_ANIM_WALK  , AOF_LOOPING  | AOF_NORESTART );
#line 245 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 246 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_COMMANDER ){
#line 247 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_IDLE_ANIM_WALK  , AOF_LOOPING  | AOF_NORESTART );
#line 248 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 249 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 251 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::RotatingAnim(void) {
#line 252 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
RunningAnim  ();
#line 253 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 256 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::IdleSound(void) {
#line 257 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PlaySound  (m_soSound  , SOUND_IDLE  , SOF_3D );
#line 258 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 260 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::SightSound(void) {
#line 261 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PlaySound  (m_soSound  , SOUND_SIGHT  , SOF_3D );
#line 262 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 264 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::WoundSound(void) {
#line 265 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PlaySound  (m_soSound  , SOUND_WOUND  , SOF_3D );
#line 266 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 268 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::DeathSound(void) {
#line 269 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PlaySound  (m_soSound  , SOUND_DEATH  , SOF_3D );
#line 270 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 273 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::EnemyPostInit(void) 
#line 274 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
{
#line 276 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_soFire1  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 277 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_soFire2  . Set3DParameters  (160.0f , 50.0f , 1.0f , 1.0f);
#line 278 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 281 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
BOOL CGrunt::CanFireAtPlayer(void) {
#line 283 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
FLOAT3D vSource  , vTarget ;
#line 284 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
GetPositionCastRay  (this  , m_penEnemy  , vSource  , vTarget );
#line 287 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CPlacement3D plBullet ;
#line 288 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_OrientationAngle  = ANGLE3D (0 , 0 , 0);
#line 289 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 290 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_PositionVector  = FIREPOS_SOLDIER ;
#line 291 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else {
#line 292 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_PositionVector  = FIREPOS_COMMANDER_DN ;
#line 293 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 294 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . RelativeToAbsolute  (GetPlacement  ());
#line 295 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
vSource  = plBullet  . pl_PositionVector ;
#line 298 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CCastRay  crRay  (this  , vSource  , vTarget );
#line 299 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
crRay  . cr_ttHitModels  = CCastRay  :: TT_NONE ;
#line 300 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
crRay  . cr_bHitTranslucentPortals  = FALSE ;
#line 301 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
en_pwoWorld  -> CastRay  (crRay );
#line 303 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return (crRay  . cr_penHit  == NULL );
#line 304 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 307 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::PrepareBullet(FLOAT fDamage) {
#line 309 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CPlacement3D plBullet ;
#line 310 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_OrientationAngle  = ANGLE3D (0 , 0 , 0);
#line 311 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 312 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_PositionVector  = FIREPOS_SOLDIER ;
#line 313 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else {
#line 314 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_PositionVector  = FIREPOS_COMMANDER_DN ;
#line 315 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 316 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . RelativeToAbsolute  (GetPlacement  ());
#line 319 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CEntityPointer penBullet  = CreateEntity  (plBullet  , CLASS_BULLET );
#line 322 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
EBulletInit  eInit ;
#line 323 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
eInit  . penOwner  = this ;
#line 324 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
eInit  . fDamage  = fDamage ;
#line 325 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
penBullet  -> Initialize  (eInit );
#line 328 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . CalcTarget  (m_penEnemy  , 250);
#line 329 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . LaunchBullet  (TRUE  , TRUE  , TRUE );
#line 330 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . DestroyBullet  ();
#line 331 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 334 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::FireBullet(void) {
#line 336 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_bFireBulletCount  ++;
#line 337 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_bFireBulletCount  > 1){m_bFireBulletCount  = 0;}
#line 338 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_bFireBulletCount  == 1){return ;}
#line 341 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CPlacement3D plBullet ;
#line 342 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_OrientationAngle  = ANGLE3D (0 , 0 , 0);
#line 343 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 344 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_PositionVector  = FIREPOS_SOLDIER ;
#line 345 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else {
#line 346 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_PositionVector  = FIREPOS_COMMANDER_DN ;
#line 347 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 348 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . RelativeToAbsolute  (GetPlacement  ());
#line 351 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CEntityPointer penBullet  = CreateEntity  (plBullet  , CLASS_BULLET );
#line 354 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
EBulletInit  eInit ;
#line 355 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
eInit  . penOwner  = this ;
#line 356 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
eInit  . fDamage  = BULLET_DAMAGE ;
#line 357 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
penBullet  -> Initialize  (eInit );
#line 360 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . CalcTarget  (m_penEnemy  , 250);
#line 361 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . CalcJitterTarget  (18.0f);
#line 362 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . LaunchBullet  (TRUE  , TRUE  , TRUE );
#line 363 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . DestroyBullet  ();
#line 364 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
  
#line 367 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
void CGrunt::FireShotgun(void) {
#line 369 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PrepareBullet  (BULLET_DAMAGE );
#line 372 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
for(INDEX i  = 0;i  < 7;i  ++){
#line 373 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CPlacement3D plBullet ;
#line 374 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_OrientationAngle  = ANGLE3D (0 , 0 , 0);
#line 375 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gtType  == GT_SOLDIER ){
#line 376 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_PositionVector  = FIREPOS_SOLDIER ;
#line 377 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else {
#line 378 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . pl_PositionVector  = FIREPOS_COMMANDER_DN ;
#line 379 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 380 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
plBullet  . RelativeToAbsolute  (GetPlacement  ());
#line 383 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CEntityPointer penBullet  = CreateEntity  (plBullet  , CLASS_BULLET );
#line 386 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
EBulletInit  eInit ;
#line 387 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
eInit  . penOwner  = this ;
#line 388 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
eInit  . fDamage  = BULLET_DAMAGE ;
#line 389 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
penBullet  -> Initialize  (eInit );
#line 392 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . CalcTarget  (m_penEnemy  , 250);
#line 393 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . CalcJitterTarget  (35.0f);
#line 394 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . LaunchBullet  (TRUE  , TRUE  , TRUE );
#line 395 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
((CBullet  &) * penBullet ) . DestroyBullet  ();
#line 396 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 397 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
BOOL CGrunt::
#line 404 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SoldierAttack(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGrunt_SoldierAttack
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGrunt::SoldierAttack expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 405 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StandingAnimFight  ();
#line 406 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetTimerAfter(0.2f + FRnd  () * 0.25f);
Jump(STATE_CURRENT, 0x01570001, FALSE, EBegin());return TRUE;}BOOL CGrunt::H0x01570001_SoldierAttack_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGrunt::H0x01570002_SoldierAttack_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570002
;
#line 409 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fFireTime  = _pTimer  -> CurrentTick  () + 4.0f;
#line 410 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_bFireBulletCount  = 0;
#line 411 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PlaySound  (m_soFire1  , SOUND_FIRE_1  , SOF_3D  | SOF_LOOP );
#line 412 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_ELITE_ANIM_FIRE  , AOF_LOOPING  | AOF_NORESTART );
#line 414 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
Jump(STATE_CURRENT,0x01570005, FALSE, EInternal());return TRUE;}BOOL CGrunt::H0x01570005_SoldierAttack_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570005
if(!(m_fFireTime  > _pTimer  -> CurrentTick  ())){ Jump(STATE_CURRENT,0x01570006, FALSE, EInternal());return TRUE;}
#line 415 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetTimerAfter(0.05f);
Jump(STATE_CURRENT, 0x01570003, FALSE, EBegin());return TRUE;}BOOL CGrunt::H0x01570003_SoldierAttack_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570003
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;

#line 418 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
FireBullet  ();
#line 420 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(! IsInPlaneFrustum  (m_penEnemy  , CosFast  (5.0f))){
#line 421 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fMoveSpeed  = 0.0f;
#line 422 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_aRotateSpeed  = 4000.0f;
#line 423 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else {
#line 424 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fMoveSpeed  = 0.0f;
#line 425 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_aRotateSpeed  = 0.0f;
#line 426 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 427 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetDesiredMovement  ();
#line 428 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return TRUE;
#line 429 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01570004, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 431 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}return TRUE;}BOOL CGrunt::H0x01570004_SoldierAttack_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570004
Jump(STATE_CURRENT,0x01570005, FALSE, EInternal());return TRUE;
#line 432 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}BOOL CGrunt::H0x01570006_SoldierAttack_06(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570006

#line 434 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_soFire1  . Stop  ();
#line 435 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fShootTime  = _pTimer  -> CurrentTick  () + m_fAttackFireTime  * (1.0f + FRnd  () / 3.0f);
#line 436 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
Return(STATE_CURRENT,EEnd  ());
#line 436 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CGrunt::
#line 440 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
CommanderAttack(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGrunt_CommanderAttack
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGrunt::CommanderAttack expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 441 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StandingAnimFight  ();
#line 442 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetTimerAfter(0.2f + FRnd  () * 0.25f);
Jump(STATE_CURRENT, 0x01570008, FALSE, EBegin());return TRUE;}BOOL CGrunt::H0x01570008_CommanderAttack_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570008
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570009, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGrunt::H0x01570009_CommanderAttack_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570009
;
#line 445 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fFireTime  = _pTimer  -> CurrentTick  () + 4.0f;
#line 446 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_bFireBulletCount  = 0;
#line 447 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PlaySound  (m_soFire1  , SOUND_FIRE_1  , SOF_3D  | SOF_LOOP );
#line 448 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_IDLE_ANIM_FIRE  , AOF_LOOPING  | AOF_NORESTART );
#line 450 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
Jump(STATE_CURRENT,0x0157000c, FALSE, EInternal());return TRUE;}BOOL CGrunt::H0x0157000c_CommanderAttack_05(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000c
if(!(m_fFireTime  > _pTimer  -> CurrentTick  ())){ Jump(STATE_CURRENT,0x0157000d, FALSE, EInternal());return TRUE;}
#line 451 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetTimerAfter(0.05f);
Jump(STATE_CURRENT, 0x0157000a, FALSE, EBegin());return TRUE;}BOOL CGrunt::H0x0157000a_CommanderAttack_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000a
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;

#line 454 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
FireBullet  ();
#line 456 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(! IsInPlaneFrustum  (m_penEnemy  , CosFast  (5.0f))){
#line 457 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fMoveSpeed  = 0.0f;
#line 458 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_aRotateSpeed  = 4000.0f;
#line 459 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else {
#line 460 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fMoveSpeed  = 0.0f;
#line 461 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_aRotateSpeed  = 0.0f;
#line 462 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 463 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetDesiredMovement  ();
#line 464 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return TRUE;
#line 465 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x0157000b, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 467 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}return TRUE;}BOOL CGrunt::H0x0157000b_CommanderAttack_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000b
Jump(STATE_CURRENT,0x0157000c, FALSE, EInternal());return TRUE;
#line 468 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}BOOL CGrunt::H0x0157000d_CommanderAttack_06(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000d

#line 470 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_soFire1  . Stop  ();
#line 471 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fShootTime  = _pTimer  -> CurrentTick  () + m_fAttackFireTime  * (1.0f + FRnd  () / 3.0f);
#line 472 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
Return(STATE_CURRENT,EEnd  ());
#line 472 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CGrunt::
#line 476 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
ShotgunAttack(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGrunt_ShotgunAttack
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGrunt::ShotgunAttack expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 477 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StandingAnimFight  ();
#line 478 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetTimerAfter(0.3f + FRnd  () * 0.2f);
Jump(STATE_CURRENT, 0x0157000f, FALSE, EBegin());return TRUE;}BOOL CGrunt::H0x0157000f_ShotgunAttack_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157000f
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570010, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGrunt::H0x01570010_ShotgunAttack_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570010
;
#line 480 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
PlaySound  (m_soFire1  , SOUND_FIRE_2  , SOF_3D  | SOF_LOOP );
#line 481 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StartModelAnim  (MERC_IDLE_ANIM_FIRE  , 0);
#line 482 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
FireShotgun  ();
#line 484 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetTimerAfter(0.5f);
Jump(STATE_CURRENT, 0x01570011, FALSE, EBegin());return TRUE;}BOOL CGrunt::H0x01570011_ShotgunAttack_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570011
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x01570012, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CGrunt::H0x01570012_ShotgunAttack_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570012
;
#line 487 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fShootTime  = _pTimer  -> CurrentTick  () + 1.5f + FRnd  () * 0.5f;
#line 488 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
Return(STATE_CURRENT,EEnd  ());
#line 488 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CGrunt::
#line 491 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
Fire(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGrunt_Fire
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGrunt::Fire expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 492 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(!(m_gtType  == GT_SOLDIER )){ Jump(STATE_CURRENT,0x0157001f, FALSE, EInternal());return TRUE;}
#line 493 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
STATE_CGrunt_SoldierAttack, TRUE;
Jump(STATE_CURRENT, 0x01570014, FALSE, EBegin());return TRUE;}BOOL CGrunt::H0x01570014_Fire_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570014
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CGrunt_SoldierAttack, TRUE, EVoid());return TRUE;case EVENTCODE_EEnd: Jump(STATE_CURRENT,0x01570015, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CGrunt::H0x01570015_Fire_02(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570015
const EEnd&__e= (EEnd&)__eeInput;
;Jump(STATE_CURRENT,0x0157001e, FALSE, EInternal());return TRUE;}BOOL CGrunt::H0x0157001f_Fire_12(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001f
if(!(m_gtType  == GT_COMMANDER )){ Jump(STATE_CURRENT,0x0157001d, FALSE, EInternal());return TRUE;}
#line 495 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(!(m_gwtWeapon  == GWT_AUTO_RIFLE )){ Jump(STATE_CURRENT,0x0157001c, FALSE, EInternal());return TRUE;}
#line 496 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
STATE_CGrunt_CommanderAttack, TRUE;
Jump(STATE_CURRENT, 0x01570016, FALSE, EBegin());return TRUE;}BOOL CGrunt::H0x01570016_Fire_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570016
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CGrunt_CommanderAttack, TRUE, EVoid());return TRUE;case EVENTCODE_EEnd: Jump(STATE_CURRENT,0x01570017, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CGrunt::H0x01570017_Fire_04(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570017
const EEnd&__e= (EEnd&)__eeInput;
;Jump(STATE_CURRENT,0x0157001b, FALSE, EInternal());return TRUE;}BOOL CGrunt::H0x0157001c_Fire_09(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001c
if(!(m_gwtWeapon  == GWT_SHOTGUN )){ Jump(STATE_CURRENT,0x0157001a, FALSE, EInternal());return TRUE;}
#line 498 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
STATE_CGrunt_ShotgunAttack, TRUE;
Jump(STATE_CURRENT, 0x01570018, FALSE, EBegin());return TRUE;}BOOL CGrunt::H0x01570018_Fire_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570018
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: Call(STATE_CURRENT, STATE_CGrunt_ShotgunAttack, TRUE, EVoid());return TRUE;case EVENTCODE_EEnd: Jump(STATE_CURRENT,0x01570019, FALSE, __eeInput); return TRUE;default: return FALSE; }}BOOL CGrunt::H0x01570019_Fire_06(const CEntityEvent &__eeInput){
#undef STATE_CURRENT
#define STATE_CURRENT 0x01570019
const EEnd&__e= (EEnd&)__eeInput;
;Jump(STATE_CURRENT,0x0157001a, FALSE, EInternal());return TRUE;}BOOL CGrunt::H0x0157001a_Fire_07(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001a
Jump(STATE_CURRENT,0x0157001b, FALSE, EInternal());return TRUE;}
BOOL CGrunt::H0x0157001b_Fire_08(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001b
Jump(STATE_CURRENT,0x0157001d, FALSE, EInternal());return TRUE;}BOOL CGrunt::H0x0157001d_Fire_10(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001d
Jump(STATE_CURRENT,0x0157001e, FALSE, EInternal());return TRUE;}
BOOL CGrunt::H0x0157001e_Fire_11(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0157001e

#line 501 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
Return(STATE_CURRENT,EReturn  ());
#line 501 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CGrunt::
#line 507 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CGrunt_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CGrunt::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 509 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
InitAsModel  ();
#line 510 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetPhysicsFlags  (EPF_MODEL_WALKING  | EPF_HASLUNGS );
#line 511 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetCollisionFlags  (ECF_MODEL );
#line 512 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetFlags  (GetFlags  () | ENF_ALIVE );
#line 513 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
en_tmMaxHoldBreath  = 5.0f;
#line 514 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
en_fDensity  = 2000.0f;
#line 518 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
switch(m_gtType ){
#line 519 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
case GT_SOLDIER : 
#line 521 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetModel  (MODEL_GRUNT );
#line 522 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetModelMainTexture  (TEXTURE_SOLDIER );
#line 523 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
AddAttachment  (MERC_ELITE_ATTACHMENT_P90_MERC  , MODEL_GUN_SOLDIER  , TEXTURE_GUN_SOLDIER );
#line 525 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fWalkSpeed  = FRnd  () + 2.5f;
#line 526 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 500.0f);
#line 527 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fAttackRunSpeed  = FRnd  () + 6.5f;
#line 528 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 529 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fCloseRunSpeed  = FRnd  () + 6.5f;
#line 530 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 532 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fAttackDistance  = 80.0f;
#line 533 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fCloseDistance  = 0.0f;
#line 534 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fStopDistance  = 8.0f;
#line 535 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fAttackFireTime  = 2.0f;
#line 536 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fCloseFireTime  = 1.0f;
#line 537 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fIgnoreRange  = 200.0f;
#line 539 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fBlowUpAmount  = 80.0f;
#line 540 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fBodyParts  = 4;
#line 541 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fDamageWounded  = 0.0f;
#line 542 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_iScore  = 500;
#line 543 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetHealth  (40.0f);
#line 544 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fMaxHealth  = 40.0f;
#line 546 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
GetModelObject  () -> StretchModel  (FLOAT3D (STRETCH_SOLDIER  , STRETCH_SOLDIER  , STRETCH_SOLDIER ));
#line 547 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
break ;
#line 549 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
case GT_COMMANDER : 
#line 551 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetModel  (MODEL_GRUNT_COMMANDER );
#line 552 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetModelMainTexture  (TEXTURE_COMMANDER );
#line 555 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
if(m_gwtWeapon  == GWT_SHOTGUN ){
#line 556 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fAttackDistance  = 50.0f;
#line 557 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fAttackFireTime  = 1.5f;
#line 558 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
AddAttachment  (MERC_IDLE_ATTACHMENT_AG36_MERC  , MODEL_SHOTGUN  , TEXTURE_SHOTGUN );
#line 559 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
AddAttachment  (MERC_IDLE_ATTACHMENT_SH_NV  , MODEL_SHIM_IN  , TEXTURE_SHIM_IN );
#line 560 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}else {
#line 561 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
AddAttachment  (MERC_IDLE_ATTACHMENT_AG36_MERC  , MODEL_GUN_COMMANDER  , TEXTURE_GUN_COMMANDER );
#line 562 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
AddAttachment  (MERC_IDLE_ATTACHMENT_SH_NV  , MODEL_SHELM_COMMANDER  , TEXTURE_SHELM_COMMANDER );
#line 563 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 565 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fWalkSpeed  = FRnd  () + 2.5f;
#line 566 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_aWalkRotateSpeed  = AngleDeg  (FRnd  () * 10.0f + 500.0f);
#line 567 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fAttackRunSpeed  = FRnd  () + 8.0f;
#line 568 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_aAttackRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 569 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fCloseRunSpeed  = FRnd  () + 8.0f;
#line 570 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_aCloseRotateSpeed  = AngleDeg  (FRnd  () * 50 + 245.0f);
#line 572 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fAttackDistance  = 90.0f;
#line 573 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fCloseDistance  = 0.0f;
#line 574 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fStopDistance  = 15.0f;
#line 575 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fAttackFireTime  = 4.0f;
#line 576 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fCloseFireTime  = 2.0f;
#line 578 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fIgnoreRange  = 200.0f;
#line 580 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fBodyParts  = 5;
#line 581 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fDamageWounded  = 0.0f;
#line 582 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_iScore  = 800;
#line 583 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
SetHealth  (60.0f);
#line 584 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
m_fMaxHealth  = 60.0f;
#line 586 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
GetModelObject  () -> StretchModel  (FLOAT3D (STRETCH_COMMANDER  , STRETCH_COMMANDER  , STRETCH_COMMANDER ));
#line 587 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
break ;
#line 588 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
}
#line 590 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
ModelChangeNotify  ();
#line 591 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
StandingAnim  ();
#line 594 "V:/Programs/SamSDK/Sources/EntitiesMP/Grunt.es"
Jump(STATE_CURRENT, STATE_CEnemyBase_MainLoop, FALSE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};