/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"

#include "StdH.h"
#include "EntitiesMP/Player.h"
#include "EntitiesMP/PlayerWeapons.h"

#include <EntitiesMP/PlayerView.h>
#include <EntitiesMP/PlayerView_tables.h>
CEntityEvent *EViewInit::MakeCopy(void) { CEntityEvent *peeCopy = new EViewInit(*this); return peeCopy;}
EViewInit::EViewInit() : CEntityEvent(EVENTCODE_EViewInit) {;
 ClearToDefault(penOwner);
 ClearToDefault(penCamera);
 ClearToDefault(vtView);
 ClearToDefault(bDeathFixed);
};
#line 24 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"


void CPlayerView_Precache(void) 
{
  CDLLEntityClass *pdec = &CPlayerView_DLLClass;
  pdec->PrecacheModel(MODEL_MARKER);
  pdec->PrecacheTexture(TEXTURE_MARKER);
}


void CPlayerView::SetDefaultProperties(void) {
  m_penOwner = NULL;
  m_iViewType = 0;
  m_fDistance = 1.0f;
  m_vZLast = FLOAT3D(0 , 0 , 0);
  m_vTargetLast = FLOAT3D(0 , 0 , 0);
  m_bFixed = FALSE ;
  m_penPrediction = NULL;
  CMovableEntity::SetDefaultProperties();
}
  
#line 54 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
void CPlayerView::AddDependentsToPrediction(void) 
#line 55 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
{
#line 56 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m_penOwner  -> AddToPrediction  ();
#line 57 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
  
#line 58 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
void CPlayerView::PreMoving() {}
  
#line 59 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
void CPlayerView::DoMoving() {
#line 60 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
en_plLastPlacement  = GetPlacement  ();
#line 61 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
  
#line 62 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
void CPlayerView::PostMoving() 
#line 63 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
{
#line 64 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
SetCameraPosition  ();
#line 65 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
  
#line 66 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
CPlacement3D CPlayerView::GetLerpedPlacement(void)const 
#line 67 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
{
#line 68 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT fLerpFactor ;
#line 69 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
if(IsPredictor  ()){
#line 70 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
fLerpFactor  = _pTimer  -> GetLerpFactor  ();
#line 71 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}else {
#line 72 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
fLerpFactor  = _pTimer  -> GetLerpFactor2  ();
#line 73 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 74 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
return LerpPlacementsPrecise  (en_plLastPlacement  , en_plPlacement  , fLerpFactor );
#line 76 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
  
#line 79 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
void CPlayerView::RenderParticles(void) 
#line 80 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
{
#line 81 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
if(Particle_GetViewer  () == this ){
#line 82 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
Particles_ViewerLocal  (this );
#line 83 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 84 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
  
#line 86 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
void CPlayerView::SetCameraPosition() 
#line 87 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
{
#line 89 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT fDistance  = 1.0f;
#line 90 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
CPlacement3D pl  = ((CPlayerEntity  &) * m_penOwner ) . en_plViewpoint ;
#line 91 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
BOOL bFollowCrossHair ;
#line 93 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
if(m_iViewType  == VT_3RDPERSONVIEW ){
#line 95 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
pl  . pl_OrientationAngle  (2) -= 12.0f;
#line 96 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  (2) += 1.0f;
#line 97 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
fDistance  = 4.2f;
#line 98 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
bFollowCrossHair  = TRUE ;
#line 100 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}else if(m_iViewType  == VT_PLAYERDEATH ){
#line 101 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
fDistance  = 3.5f;
#line 102 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
bFollowCrossHair  = FALSE ;
#line 103 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 105 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
pl  . pl_OrientationAngle  (3) = 0.0f;
#line 108 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
pl  . RelativeToAbsolute  (m_penOwner  -> GetPlacement  ());
#line 110 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT3D vBase ;
#line 111 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
EntityInfo  * pei  = (EntityInfo  *) (m_penOwner  -> GetEntityInfo  ());
#line 112 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
GetEntityInfoPosition  (m_penOwner  , pei  -> vSourceCenter  , vBase );
#line 115 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOATmatrix3D m ;
#line 116 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
MakeRotationMatrixFast  (m  , pl  . pl_OrientationAngle );
#line 117 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT3D vRight  = m  . GetColumn  (1);
#line 118 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT3D vUp  = m  . GetColumn  (2);
#line 119 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT3D vFront  = m  . GetColumn  (3);
#line 121 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT3D vDest  [ 5 ];
#line 122 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vDest  [ 0 ] = vBase  + vFront  * fDistance  + vUp  * 1.0f;
#line 123 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vDest  [ 1 ] = vBase  + vFront  * fDistance  - vUp  * 1.0f;
#line 124 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vDest  [ 2 ] = vBase  + vFront  * fDistance  + vRight  * 1.0f;
#line 125 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vDest  [ 3 ] = vBase  + vFront  * fDistance  - vRight  * 1.0f;
#line 126 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vDest  [ 4 ] = vBase  + vFront  * fDistance ;
#line 128 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT fBack  = 0;
#line 130 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
for(INDEX i  = 0;i  < 5;i  ++){
#line 132 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
CCastRay  crRay  (m_penOwner  , vBase  , vDest  [ i  ]);
#line 133 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
crRay  . cr_bHitTranslucentPortals  = FALSE ;
#line 134 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
crRay  . cr_ttHitModels  = CCastRay  :: TT_COLLISIONBOX ;
#line 135 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
GetWorld  () -> CastRay  (crRay );
#line 138 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
if(crRay  . cr_penHit  != NULL ){
#line 140 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
fDistance  = Min  (fDistance  , crRay  . cr_fHitDistance  - 0.5f);
#line 142 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
if(crRay  . cr_pbpoBrushPolygon  != NULL ){
#line 144 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT3D vDir  = (vDest  [ i  ] - vBase ) . Normalize  ();
#line 145 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT fD  = Abs  (FLOAT3D (crRay  . cr_pbpoBrushPolygon  -> bpo_pbplPlane  -> bpl_plAbsolute ) % vDir ) * 0.25f;
#line 146 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
fBack  = Max  (fBack  , fD );
#line 147 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 148 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 150 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 151 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
fDistance  = ClampDn  (fDistance  - fBack  , 0.0f);
#line 152 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m_fDistance  = fDistance ;
#line 153 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vBase  += vFront  * fDistance ;
#line 155 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
CPlayerWeapons  * ppw  = ((CPlayer  &) * m_penOwner ) . GetPlayerWeapons  ();
#line 156 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
if(bFollowCrossHair ){
#line 157 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT3D vTarget  = vBase  - ppw  -> m_vRayHit ;
#line 158 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT fLen  = vTarget  . Length  ();
#line 159 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
if(fLen  > 0.01){
#line 160 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vTarget  /= fLen ;
#line 161 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}else {
#line 162 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vTarget  = FLOAT3D (0 , 1 , 0);
#line 163 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 165 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT3D vX ;
#line 166 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT3D vY  = m  . GetColumn  (2);
#line 167 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
FLOAT3D vZ  = vTarget ;
#line 168 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vZ  . Normalize  ();
#line 170 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
if(Abs  (vY  % vZ ) > 0.9f){
#line 171 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vY  = - m  . GetColumn  (3);
#line 172 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 174 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vX  = vY  * vZ ;
#line 175 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vX  . Normalize  ();
#line 176 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vY  = vZ  * vX ;
#line 177 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
vY  . Normalize  ();
#line 178 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m_vZLast  = vZ ;
#line 180 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m  (1 , 1) = vX  (1);m  (1 , 2) = vY  (1);m  (1 , 3) = vZ  (1);
#line 181 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m  (2 , 1) = vX  (2);m  (2 , 2) = vY  (2);m  (2 , 3) = vZ  (2);
#line 182 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m  (3 , 1) = vX  (3);m  (3 , 2) = vY  (3);m  (3 , 3) = vZ  (3);
#line 183 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
DecomposeRotationMatrixNoSnap  (pl  . pl_OrientationAngle  , m );
#line 184 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 186 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
if(m_bFixed ){
#line 187 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  = GetPlacement  () . pl_PositionVector ;
#line 188 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
pl  . pl_OrientationAngle  = ANGLE3D (0 , - 90 , 0);
#line 189 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m_fDistance  = (pl  . pl_PositionVector  - m_penOwner  -> GetPlacement  () . pl_PositionVector ) . Length  ();
#line 190 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
MakeRotationMatrixFast  (m  , pl  . pl_OrientationAngle );
#line 191 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}else {
#line 192 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
pl  . pl_PositionVector  = vBase ;
#line 193 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 196 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
SetPlacement_internal  (pl  , m  , TRUE );
#line 197 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
BOOL CPlayerView::
#line 247 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPlayerView_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EViewInit, "CPlayerView::Main expects 'EViewInit' as input!");  const EViewInit &eInit = (const EViewInit &)__eeInput;
#line 249 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
ASSERT  (eInit  . penOwner  != NULL );
#line 250 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m_penOwner  = eInit  . penOwner ;
#line 251 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m_iViewType  = eInit  . vtView ;
#line 252 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m_bFixed  = eInit  . bDeathFixed ;
#line 253 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
ASSERT  (IsOfClass  (m_penOwner  , "Player"));
#line 256 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
InitAsEditorModel  ();
#line 257 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
SetFlags  (GetFlags  () | ENF_CROSSESLEVELS );
#line 258 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL  | EPF_MOVABLE );
#line 259 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 261 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
SetModel  (MODEL_MARKER );
#line 262 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
SetModelMainTexture  (TEXTURE_MARKER );
#line 265 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
if(m_iViewType  == VT_PLAYERDEATH ){
#line 266 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
AddToMovers  ();
#line 267 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}
#line 269 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
SendEvent  (EStart  ());
#line 270 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x01930001, FALSE, EBegin());return TRUE;}BOOL CPlayerView::H0x01930001_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x01930001
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;

#line 273 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
SetCameraPosition  ();
#line 274 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
en_plLastPlacement  = GetPlacement  ();
#line 275 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
m_vTargetLast  = ((CPlayer  &) * m_penOwner ) . GetPlayerWeapons  () -> m_vRayHit ;
#line 276 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
return TRUE;
#line 277 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}ASSERT(FALSE);break;case(EVENTCODE_EEnd):{const EEnd&e= (EEnd&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x01930002, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 280 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
}return TRUE;}BOOL CPlayerView::H0x01930002_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x01930002

#line 282 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
Destroy  ();
#line 284 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
Return(STATE_CURRENT,EVoid());
#line 284 "V:/Programs/SamSDK/Sources/EntitiesMP/PlayerView.es"
return TRUE; ASSERT(FALSE); return TRUE;};