/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"

#include "StdH.h"

#include <EntitiesMP/Switch.h>
#include <EntitiesMP/Switch_tables.h>
void CSwitch::SetDefaultProperties(void) {
  m_iModelONAnimation = 0;
  m_iTextureONAnimation = 0;
  m_iModelOFFAnimation = 0;
  m_iTextureOFFAnimation = 0;
  m_penTarget = NULL;
  m_eetEvent = EET_START ;
  m_eetOffEvent = EET_IGNORE ;
  m_penOffTarget = NULL;
  m_swtType = SWT_ONOFF ;
  m_strMessage = "";
  m_bSwitchON = FALSE ;
  m_penCaused = NULL;
  m_bUseable = FALSE ;
  m_bInvisible = FALSE ;
  CModelHolder2::SetDefaultProperties();
}
  
#line 47 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
CAnimData * CSwitch::GetAnimData(SLONG slPropertyOffset) 
#line 48 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
{
#line 49 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(slPropertyOffset  == offsetof  (CSwitch  , m_iModelONAnimation ) || 
#line 50 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
slPropertyOffset  == offsetof  (CSwitch  , m_iModelOFFAnimation )){
#line 51 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return GetModelObject  () -> GetData  ();
#line 52 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}else if(slPropertyOffset  == offsetof  (CSwitch  , m_iTextureONAnimation ) || 
#line 53 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
slPropertyOffset  == offsetof  (CSwitch  , m_iTextureOFFAnimation )){
#line 54 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return GetModelObject  () -> mo_toTexture  . GetData  ();
#line 55 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}else {
#line 56 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return CModelHolder2  :: GetAnimData  (slPropertyOffset );
#line 57 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 58 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
  
#line 61 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
BOOL CSwitch::CanReactOnEntity(CEntity * pen) 
#line 62 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
{
#line 63 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(pen  == NULL ){
#line 64 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return FALSE ;
#line 65 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 67 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(! (pen  -> GetFlags  () & ENF_ALIVE )){
#line 68 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return FALSE ;
#line 69 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 71 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return TRUE ;
#line 72 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
  
#line 76 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SLONG CSwitch::GetUsedMemory(void) 
#line 77 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
{
#line 79 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SLONG  slUsedMemory  = sizeof  (CSwitch ) - sizeof  (CModelHolder2 ) + CModelHolder2  :: GetUsedMemory  ();
#line 81 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
slUsedMemory  += m_strMessage  . Length  ();
#line 82 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return slUsedMemory ;
#line 83 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
BOOL CSwitch::
#line 91 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SwitchON(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSwitch_SwitchON
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSwitch::SwitchON expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 93 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(m_bSwitchON ){
#line 95 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Return(STATE_CURRENT,EVoid());
#line 95 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return TRUE;
#line 96 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 98 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
GetModelObject  () -> PlayAnim  (m_iModelONAnimation  , 0);
#line 99 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
GetModelObject  () -> mo_toTexture  . PlayAnim  (m_iTextureONAnimation  , 0);
#line 100 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bSwitchON  = TRUE ;
#line 102 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SendToTarget  (m_penTarget  , m_eetEvent  , m_penCaused );
#line 104 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (m_iModelONAnimation ));
Jump(STATE_CURRENT, 0x00d10001, FALSE, EBegin());return TRUE;}BOOL CSwitch::H0x00d10001_SwitchON_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10001
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x00d10002, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;
return FALSE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 106 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}return TRUE;}BOOL CSwitch::H0x00d10002_SwitchON_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10002

#line 108 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Return(STATE_CURRENT,EReturn  ());
#line 108 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CSwitch::
#line 112 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SwitchOFF(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSwitch_SwitchOFF
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSwitch::SwitchOFF expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 114 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(! m_bSwitchON ){
#line 116 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Return(STATE_CURRENT,EVoid());
#line 116 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return TRUE;
#line 117 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 119 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
GetModelObject  () -> PlayAnim  (m_iModelOFFAnimation  , 0);
#line 120 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
GetModelObject  () -> mo_toTexture  . PlayAnim  (m_iTextureOFFAnimation  , 0);
#line 121 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bSwitchON  = FALSE ;
#line 123 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(m_penOffTarget  != NULL )
#line 124 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
{
#line 125 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SendToTarget  (m_penOffTarget  , m_eetOffEvent  , m_penCaused );
#line 126 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 127 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
else 
#line 128 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
{
#line 130 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SendToTarget  (m_penTarget  , m_eetOffEvent  , m_penCaused );
#line 131 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 133 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SetTimerAfter(GetModelObject  () -> GetAnimLength  (m_iModelOFFAnimation ));
Jump(STATE_CURRENT, 0x00d10004, FALSE, EBegin());return TRUE;}BOOL CSwitch::H0x00d10004_SwitchOFF_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10004
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x00d10005, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;
return FALSE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 135 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}return TRUE;}BOOL CSwitch::H0x00d10005_SwitchOFF_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10005

#line 137 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Return(STATE_CURRENT,EReturn  ());
#line 137 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CSwitch::
#line 140 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
MainLoop_Once(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSwitch_MainLoop_Once
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSwitch::MainLoop_Once expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 141 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bUseable  = TRUE ;
#line 144 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00d10007, FALSE, EBegin());return TRUE;}BOOL CSwitch::H0x00d10007_MainLoop_Once_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10007
switch(__eeInput.ee_slEvent){case(EVENTCODE_ETrigger):{const ETrigger&eTrigger= (ETrigger&)__eeInput;

#line 147 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(CanReactOnEntity  (eTrigger  . penCaused ) && m_bUseable ){
#line 148 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 149 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_penCaused  = eTrigger  . penCaused ;
#line 150 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchON, TRUE, EVoid());return TRUE;
#line 151 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 152 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;

#line 155 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 156 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchON, TRUE, EVoid());return TRUE;
#line 157 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):{const EStop&e= (EStop&)__eeInput;

#line 160 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 161 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchOFF, TRUE, EVoid());return TRUE;
#line 162 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EReturn):{const EReturn&e= (EReturn&)__eeInput;

#line 164 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bUseable  = ! m_bSwitchON ;
#line 165 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return TRUE;
#line 166 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 167 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}return TRUE;}BOOL CSwitch::H0x00d10008_MainLoop_Once_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d10008
 ASSERT(FALSE); return TRUE;};BOOL CSwitch::
#line 170 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
MainLoop_OnOff(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSwitch_MainLoop_OnOff
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSwitch::MainLoop_OnOff expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 171 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bUseable  = TRUE ;
#line 174 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00d1000a, FALSE, EBegin());return TRUE;}BOOL CSwitch::H0x00d1000a_MainLoop_OnOff_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d1000a
switch(__eeInput.ee_slEvent){case(EVENTCODE_ETrigger):{const ETrigger&eTrigger= (ETrigger&)__eeInput;

#line 177 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(CanReactOnEntity  (eTrigger  . penCaused ) && m_bUseable ){
#line 178 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 179 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_penCaused  = eTrigger  . penCaused ;
#line 181 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(m_bSwitchON ){
#line 182 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchOFF, TRUE, EVoid());return TRUE;
#line 184 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}else {
#line 185 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchON, TRUE, EVoid());return TRUE;
#line 186 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 187 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 188 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;

#line 191 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 192 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchON, TRUE, EVoid());return TRUE;
#line 193 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):{const EStop&e= (EStop&)__eeInput;

#line 196 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bUseable  = FALSE ;
#line 197 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Call(STATE_CURRENT, STATE_CSwitch_SwitchOFF, TRUE, EVoid());return TRUE;
#line 198 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;

#line 201 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(m_penDestruction  != NULL ){
#line 202 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Jump(STATE_CURRENT, STATE_CModelHolder2_Die, FALSE, EVoid());return TRUE;
#line 203 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 204 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return TRUE;
#line 205 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;case(EVENTCODE_EReturn):{const EReturn&e= (EReturn&)__eeInput;

#line 207 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
m_bUseable  = TRUE ;
#line 208 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return TRUE;
#line 209 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 210 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}return TRUE;}BOOL CSwitch::H0x00d1000b_MainLoop_OnOff_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00d1000b
 ASSERT(FALSE); return TRUE;};BOOL CSwitch::
#line 213 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSwitch_Main
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSwitch::Main expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput;
#line 215 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
CModelHolder2  :: InitModelHolder  ();
#line 217 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(m_bInvisible ){
#line 218 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
SwitchToEditorModel  ();
#line 219 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 221 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
if(m_swtType  == SWT_ONCE ){
#line 222 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Jump(STATE_CURRENT, STATE_CSwitch_MainLoop_Once, TRUE, EVoid());return TRUE;
#line 223 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}else {
#line 224 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Jump(STATE_CURRENT, STATE_CSwitch_MainLoop_OnOff, TRUE, EVoid());return TRUE;
#line 225 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
}
#line 227 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
Return(STATE_CURRENT,EVoid());
#line 227 "V:/Programs/SamSDK/Sources/EntitiesMP/Switch.es"
return TRUE; ASSERT(FALSE); return TRUE;};